# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7acab173a6a43d69e30afb2cabc8a67a1d667e52e8aa1f4bb208929fec4ff1c64f03b9e34eac56f56d435afea90bac907ce4c34cd105015890663de24ca8bad0

test:
  secret_key_base: 612c54158cad28128a45f393aea7ab94c03ca3ea99d3b1f978e81f91bcde6bdb3b653a89fd362a642d2394217eaa1847d0b605d1c02e7e61e30ebbf130243e82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
